const ACTIONS = {
  SONGS: {
    GET_NEW_RELEASE: {
      INIT: 'GET_NEW_RELEASE_INIT',
      SUCCESS: 'GET_NEW_RELEASE_SUCCESS',
      FAILED: 'GET_NEW_RELEASE_FAILED'
    },
    FEATURED_PLAY_LIST: {
      INIT: 'GET_FEATURED_PLAY_LIST_INIT',
      SUCCESS: 'GET_FEATURED_PLAY_LIST_SUCCESS',
      FAILED: 'GET_FEATURED_PLAY_LIST_FAILED'
    },
    GET_CATEGORIES: {
      INIT: 'GET_CATEGORIES_INIT',
      SUCCESS: 'GET_CATEGORIES_SUCCESS',
      FAILED: 'GET_CATEGORIES_FAILED'
    }
  }
}

export default ACTIONS;